name: Deploy Frontend (Vite React)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub 레포지토리 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Node.js 환경 설정 및 corepack 활성화 (yarn 자동 활성화)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Change directory to LittlePet_Front
        run: cd LittlePet_Front

      # 3. Vite React 프로젝트 빌드
      - name: Install dependencies and build (Vite)
        run: |
          cd LittlePet_Front
          corepack enable
          yarn install
          yarn build

      # 4. Docker 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # 5. Docker 이미지 빌드 및 푸시
      - name: Docker Image Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/littlepet-frontend:latest

      # 6. EC2 서버에서 최신 Docker 이미지 실행
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu
            docker-compose stop frontend
            docker rmi -f $(docker images ${{ secrets.DOCKER_USERNAME }}/littlepet-frontend -q) || true  # 기존 이미지 삭제
            docker-compose frontend
            docker-compose up -d --build frontend